Repository shareYourProject/front-end, pull requests merged in 2020-06, with the labels that each got.

#192 💄 Update Basic UI
  src/app/pages/home/home.component.html
Labels: enhancement, integration

#193 Logout refresh
  src/app/components/core/navbar/navbar.component.html
  src/app/components/core/navbar/navbar.component.ts
Labels: enhancement

#194 Create post redirection
  src/app/pages/project/project-dashboard/project-dashboard.component.html
  src/app/pages/project/project-dashboard/project-dashboard.component.ts
Labels: enhancement

#191 Feed page
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/pages/feed/feed.component.html
  src/app/pages/feed/feed.component.scss
  src/app/pages/feed/feed.component.spec.ts
  src/app/pages/feed/feed.component.ts
  src/app/services/search.service.ts
Labels: enhancement, integration, ready for HTML/CSS

#198 🐛 fix #195
  src/app/app-routing.module.ts
Labels: bug

#199 🐛 fix #177
  src/app/models/classes/Project.ts
  src/app/pages/project/project-members/project-members.component.html
  src/app/pages/project/project-members/project-members.component.ts
Labels: bug

#200 Api permissions guard
  src/app/app-routing.module.ts
  src/app/guards/permissions.guard.spec.ts
  src/app/guards/permissions.guard.ts
Labels: enhancement

#203 💄 Update Login Register UI
  src/app/pages/login/login.component.html
  src/app/pages/register/register.component.html
Labels: enhancement, integration

#205 💄 Update Icons Followed Project Page
  src/app/pages/project-public/project-public.component.html
  src/app/pages/project-public/project-public.component.ts
Labels: enhancement, integration

#206 💄 Add Settings Link in NavBar
  src/app/components/core/navbar/navbar.component.ts
Labels: enhancement, integration

#207 💄 Add random picture for project
  src/app/components/core/post-card/post-card.component.html
  src/app/components/project-card/project-card.component.html
  src/app/pages/project-public/project-public.component.html
  src/app/pages/project/project-main/project-main.component.html
Labels: enhancement, integration

#208 💄 Update Comment UI
  src/app/pages/post-page/post-page.component.html
  src/app/pages/post-page/post-page.component.scss
  src/app/pages/post-page/post-page.component.ts
Labels: enhancement, integration
