Repository shareYourProject/front-end, pull requests merged in 2020-05, with the labels that each got.

#9 integration: Post page
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/pages/post-page/post-page.component.html
  src/app/pages/post-page/post-page.component.scss
  src/app/pages/post-page/post-page.component.spec.ts
  src/app/pages/post-page/post-page.component.ts
Labels: integration

#5 Implement server API client side
  src/app/app.module.ts
  src/app/dev/fakeBackEnd.ts
  src/app/models/api/FileData.ts
  src/app/models/api/PermissionsData.ts
  src/app/models/api/PostBaseData.ts
  src/app/models/api/ProjectData.ts
  src/app/models/api/UserAccountData.ts
  src/app/models/api/UserSessionData.ts
  src/app/models/api/apiData.ts
  src/app/models/api/iuser.ts
  src/app/models/api/login-response.ts
  src/app/models/api/register-response.ts
  src/app/models/classes/ApiObject.ts
  src/app/models/classes/Comment.ts
  src/app/models/classes/File.ts
  src/app/models/classes/MergeableApiObject.ts
  src/app/models/classes/Permissions.ts
  src/app/models/classes/Post.ts
  src/app/models/classes/PostBase.ts
  src/app/models/classes/Project.ts
  src/app/models/classes/UserAccount.ts
  src/app/models/collections/CollectionBase.ts
  src/app/models/collections/CommentCollection.ts
  src/app/models/collections/MergeableCollection.ts
  src/app/models/collections/PermissionsCollection.ts
  src/app/models/collections/PostCollection.ts
  src/app/models/collections/ProjectCollection.ts
  src/app/models/collections/UserAccountCollection.ts
  src/app/models/errors/AccessDeniedApiError.ts
  src/app/models/errors/ApiError.ts
  src/app/models/errors/DefaultApiError.ts
  src/app/models/errors/DeletedDataError.ts
  src/app/models/errors/NotFoundApiError.ts
  src/app/models/errors/NotLoggedError.ts
  src/app/models/post.ts
  src/app/models/project.ts
  src/app/models/request/partial-list.ts
  src/app/models/request/post-list.ts
  src/app/models/request/post.ts
  src/app/models/request/user-account.ts
  src/app/models/resolvables/UserAccountResolvable.ts
  src/app/models/user-account.ts
  src/app/pages/login/login.component.html
  src/app/pages/login/login.component.ts
  src/app/pages/project/project-dashboard/project-dashboard.component.ts
  src/app/pages/project/project-settings/project-settings.component.ts
  src/app/regex.ts
  src/app/services/api.service.ts
  tsconfig.json
Labels: enhancement

#15 Fix api
  src/app/models/api/pagedData.ts
  src/app/models/classes/Comment.ts
  src/app/models/classes/Post.ts
  src/app/models/classes/PostBase.ts
  src/app/models/collections/CommentCollection.ts
  src/app/models/collections/PagingCollection.ts
Labels: bug, enhancement

#12 Post Page
  src/app/app.module.ts
  src/app/dev/fakeBackEnd.ts
  src/app/models/classes/Post.ts
  src/app/models/classes/PostBase.ts
  src/app/models/collections/CommentCollection.ts
  src/app/pages/login/login.component.ts
  src/app/pages/post-page/post-page.component.html
  src/app/pages/post-page/post-page.component.ts
  src/app/pages/project/project-main/project-main.component.ts
Labels: HTML, integration, ts

#17 impl api.isLogged
  src/app/dev/fakeBackEnd.ts
  src/app/guards/auth.guard.ts
  src/app/guards/not-auth.guard.ts
  src/app/services/api.service.ts
Labels: API, enhancement, p: medium

#38 Project Public Page
  src/app/dev/fakeBackEnd.ts
  src/app/pages/project-public/project-public.component.html
  src/app/pages/project-public/project-public.component.ts
Labels: integration

#42 Project-Public-Page
  src/app/app.module.ts
  src/app/components/links-list/links-list.component.html
  src/app/components/links-list/links-list.component.scss
  src/app/components/links-list/links-list.component.spec.ts
  src/app/components/links-list/links-list.component.ts
  src/app/components/user-list/user-list.component.html
  src/app/components/user-list/user-list.component.ts
  src/app/dev/fakeBackEnd.ts
  src/app/models/classes/MergeableApiObject.ts
  src/app/models/classes/Post.ts
  src/app/models/classes/PostBase.ts
  src/app/models/classes/Project.ts
  src/app/models/classes/UserAccount.ts
  src/app/models/collections/CommentCollection.ts
  src/app/models/collections/ProjectCollection.ts
  src/app/models/collections/UserAccountCollection.ts
  src/app/pages/project-public/project-public.component.html
  src/app/pages/project-public/project-public.component.scss
  src/app/pages/project-public/project-public.component.ts
  src/app/services/api.service.ts
Labels: integration, ready for HTML/CSS

#35 Login Page
  src/app/app-routing.module.ts
  src/app/pages/login/login.component.html
  src/app/pages/login/login.component.ts
Labels: integration

#58 Navbar
  src/app/app.component.html
  src/app/app.component.ts
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.ts
Labels: enhancement

#33 User Dashboard Page
  src/app/app-routing.module.ts
  src/app/pages/user/user-dashboard/user-dashboard.component.html
  src/app/pages/user/user-dashboard/user-dashboard.component.ts
Labels: integration, ready for HTML/CSS

#34 User Public Page
  src/app/app.component.html
  src/app/components/links-list/links-list.component.ts
  src/app/dev/fakeBackEnd.ts
  src/app/pages/user-public-page/user-public-page.component.html
  src/app/pages/user-public-page/user-public-page.component.scss
  src/app/pages/user-public-page/user-public-page.component.ts
Labels: integration, ready for HTML/CSS

#43 Project Dashboard Page
  src/app/components/user-list/user-list.component.html
  src/app/pages/project/project-dashboard/project-dashboard.component.html
  src/app/pages/project/project-dashboard/project-dashboard.component.ts
Labels: integration, ready for HTML/CSS

#86 call back-end logout
  src/app/services/api.service.ts
Labels: API, enhancement

#87 Restore user data when reload page
  src/app/services/api.service.ts
Labels: API, enhancement

#89 Api editable
  src/app/models/classes/ApiObject.ts
  src/app/models/classes/Comment.ts
  src/app/models/classes/EditableApiObject.ts
  src/app/models/classes/MergeableApiObject.ts
  src/app/models/classes/Post.ts
  src/app/models/classes/PostBase.ts
  src/app/models/classes/Project.ts
  src/app/models/classes/UserAccount.ts
  src/app/models/collections/ApiCollection.ts
  src/app/models/collections/CollectionBase.ts
  src/app/models/collections/CommentCollection.ts
  src/app/models/collections/MergeableCollection.ts
  src/app/models/collections/PagingCollection.ts
  src/app/models/collections/PermissionsCollection.ts
  src/app/models/collections/PostCollection.ts
  src/app/models/collections/ProjectCollection.ts
  src/app/models/collections/UserAccountCollection.ts
  src/app/models/objectInterfaces/IProject.ts
  src/app/models/objectInterfaces/IUserAccount.ts
  src/app/models/utils/ApiUtils.ts
  src/app/models/utils/DeepReadonly.ts
  src/app/services/api.service.ts
Labels: API, enhancement

#91 Api search
  src/app/models/api/SearchResult.ts
  src/app/services/search.service.spec.ts
  src/app/services/search.service.ts
Labels: API, enhancement

#93 Search page
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/dev/fakeBackEnd.ts
  src/app/pages/search/search.component.html
  src/app/pages/search/search.component.scss
  src/app/pages/search/search.component.spec.ts
  src/app/pages/search/search.component.ts
  src/app/services/search.service.ts
Labels: enhancement

#95 Navbar search bar
  src/app/components/core/navbar/navbar.component.html
  src/app/components/core/navbar/navbar.component.ts
  src/app/pages/search/search.component.ts
Labels: enhancement

#96 Skills list
  src/app/app.module.ts
  src/app/components/skills-list/skills-list.component.html
  src/app/components/skills-list/skills-list.component.scss
  src/app/components/skills-list/skills-list.component.spec.ts
  src/app/components/skills-list/skills-list.component.ts
  src/app/pages/user-public-page/user-public-page.component.html
Labels: enhancement

#97 Project card
  src/app/app.module.ts
  src/app/components/project-card/project-card.component.html
  src/app/components/project-card/project-card.component.scss
  src/app/components/project-card/project-card.component.spec.ts
  src/app/components/project-card/project-card.component.ts
  src/app/pages/user-public-page/user-public-page.component.html
Labels: enhancement

#98 User card
  src/app/app.module.ts
  src/app/components/user-card/user-card.component.html
  src/app/components/user-card/user-card.component.scss
  src/app/components/user-card/user-card.component.spec.ts
  src/app/components/user-card/user-card.component.ts
  src/app/pages/search/search.component.html
Labels: enhancement

#105 ✨ project follow / unfollow
  src/app/models/classes/Project.ts
Labels: API, enhancement

#106 Api fix link parsing
  src/app/dev/fakeBackEnd.ts
  src/app/models/api/LinkData.ts
  src/app/models/classes/Project.ts
  src/app/models/classes/UserAccount.ts
Labels: API, bug

#107 Api post rework
  src/app/models/classes/PostBase.ts
  src/app/models/classes/Project.ts
  src/app/models/classes/UserAccount.ts
  src/app/models/collections/CollectionBase.ts
  src/app/models/collections/CommentCollection.ts
  src/app/models/collections/PermissionsCollection.ts
  src/app/models/collections/PostCollection.ts
  src/app/pages/post-page/post-page.component.ts
  src/app/pages/project-public/project-public.component.ts
  src/app/pages/project/project-dashboard/project-dashboard.component.ts
  src/app/pages/user-public-page/user-public-page.component.ts
  src/app/services/api.service.ts
  src/app/services/collections.service.spec.ts
  src/app/services/collections.service.ts
  src/app/services/search.service.ts
Labels: API

#108 Api feed
  src/app/models/api/FeedResponse.ts
  src/app/services/search.service.ts
Labels: API, enhancement

#115 Update bootstrap theme
  angular.json
  src/_variables.scss
  src/styles.scss
Labels: enhancement, integration

#117 :lipstick: Update NavBar style
  src/app/components/core/navbar/navbar.component.html
  src/app/components/core/navbar/navbar.component.scss
Labels: integration

#119 🎨 enhance api object update method
  src/app/models/classes/EditableApiObject.ts
Labels: API, enhancement

#124 Api fix paged response
  src/app/models/api/PagedData.ts
  src/app/services/comment.service.ts
  src/app/utils/MakePagedResponse.ts
Labels: API, bug

#130 🚑 fix project dashboard page
  src/app/pages/project/project-dashboard/project-dashboard.component.ts
Labels: bug

#132 Fix project member load
  src/app/models/api/ProjectData.ts
  src/app/models/classes/Project.ts
Labels: API, bug

#133 Post page add comment
  src/app/pages/post-page/post-page.component.ts
  src/app/services/comment.service.ts
Labels: enhancement

#135 :lipstick: Update UI user public page
  src/app/pages/user-public-page/user-public-page.component.html
  src/app/pages/user-public-page/user-public-page.component.scss
  src/app/pages/user-public-page/user-public-page.component.ts
  src/app/services/post.service.ts
Labels: enhancement, integration, ready for HTML/CSS

#138 :heavy_plus_sign: Adding AwesomeFont
  package-lock.json
  package.json
  src/app/app.module.ts
Labels: enhancement, integration

#143 🐛 fix-140
  src/app/services/user.service.ts
Labels: API, bug

#146 Refactoring old forms
  src/app/pages/login/login.component.html
  src/app/pages/login/login.component.ts
  src/app/pages/register/register.component.html
  src/app/pages/register/register.component.ts
Labels: API, enhancement

#149 Api project permissions
  src/app/models/api/Permissions.ts
  src/app/models/api/PermissionsData.ts
  src/app/models/api/ProjectData.ts
  src/app/models/classes/Permissions.ts
  src/app/models/classes/Project.ts
  src/app/models/object interfaces/IProject.ts
  src/app/models/utils/DeepReadonly.ts
Labels: API, enhancement

#154 Update project settings ui
  angular.json
  src/app/pages/project/project-settings/project-settings.component.html
  src/app/pages/project/project-settings/project-settings.component.ts
Labels: enhancement, integration

#155 :lipstick: Update Favicon
  src/favicon.ico
Labels: enhancement

#158 :lipstick: Fix Navbar on top
  src/app/app.component.html
  src/app/app.component.scss
  src/app/components/core/navbar/navbar.component.html
Labels: bug

#152 Project members page
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/models/api/Permissions.ts
  src/app/models/classes/Project.ts
  src/app/models/object interfaces/IProject.ts
  src/app/pages/project/project-main/project-main.component.ts
  src/app/pages/project/project-members/project-members.component.html
  src/app/pages/project/project-members/project-members.component.scss
  src/app/pages/project/project-members/project-members.component.spec.ts
  src/app/pages/project/project-members/project-members.component.ts
Labels: enhancement

#145 Project create form
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/pages/project-create-form/project-create-form.component.html
  src/app/pages/project-create-form/project-create-form.component.scss
  src/app/pages/project-create-form/project-create-form.component.spec.ts
  src/app/pages/project-create-form/project-create-form.component.ts
  src/app/services/project.service.ts
Labels: enhancement, integration, ready for HTML/CSS

#163 Fix #161
  src/app/models/classes/Project.ts
  src/app/services/api-client.service.ts
Labels: API, bug

#168 ✨ add getFollowedProject
  src/app/services/project.service.ts
Labels: API, enhancement

#170 :lipstick: Improve user list UI
  src/app/components/user-list/user-list.component.html
Labels: enhancement, integration

#169 Follow buttons
  src/app/models/api/UserData.ts
  src/app/models/classes/User.ts
  src/app/pages/project-public/project-public.component.html
  src/app/pages/project-public/project-public.component.ts
  src/app/pages/user-public-page/user-public-page.component.html
  src/app/pages/user-public-page/user-public-page.component.ts
Labels: API, enhancement

#171 Post card buttons
  src/app/components/core/post-card/post-card.component.html
  src/app/components/core/post-card/post-card.component.ts
  src/app/pages/project-public/project-public.component.html
  src/app/pages/user-public-page/user-public-page.component.html
Labels: enhancement

#172 💄Update Dashbord members UI
  src/app/pages/project/project-members/project-members.component.html
  src/app/pages/project/project-members/project-members.component.scss
  src/app/pages/project/project-members/project-members.component.ts
Labels: enhancement, integration

#173 Project sub navbar links
  src/app/models/api/Permissions.ts
  src/app/models/classes/Project.ts
  src/app/pages/project/project-main/project-main.component.html
  src/app/pages/project/project-main/project-main.component.ts
Labels: enhancement

#176 ⚡️ dont show owner in member page
  src/app/models/classes/Project.ts
  src/app/pages/project/project-members/project-members.component.ts
Labels: enhancement

#179 👽 🚑 fix post create route
  src/app/services/post.service.ts
Labels: API, bug

#180 :lipstick: Update UI Dashboard Main Page
  src/app/pages/project/project-dashboard/project-dashboard.component.html
  src/app/pages/project/project-dashboard/project-dashboard.component.ts
Labels: enhancement, integration

#181 🐛 fix cors from post create request
  src/app/services/post.service.ts
Labels: API, bug

#184 💄 Update UI for research feature
  src/app/pages/search/search.component.html
Labels: enhancement, integration

#185 💄 Update User Card UI
  src/app/components/user-card/user-card.component.html
Labels: enhancement, integration
